apiVersion: v1
kind: Pod
metadata:
  name: network-test
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "while true; do wget -q --spider https://google.com && echo 'Internet is accessible'; sleep 30; done"]
