# Generated by Django 4.1 on 2024-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
