# Generated by Django 5.1.4 on 2024-12-09 20:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pickup', '0003_post_post_title_post_rsvp_list_alter_post_post_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
                ('tagged_posts', models.ManyToManyField(related_name='post_tags', to='Pickup.post')),
            ],
            options={
                'db_table': 'tag',
            },
        ),
    ]
